### ISSUE TITLE
`hex` to `hexa`

### ISSUE THREAD

**Issue by j042** [tataratat/samples#5]
I think the folder should match gustaf's geometry type. `volumes/hex` -> `volumes/hexa`. @clemens-fricke could you please help here?

**Comment by clemens-fricke** [comment]
I will fix this. Currently, it is not that bad yet since only the hmascii example https://github.com/tataratat/gustaf/pull/65 is effected.

**Comment by clemens-fricke** [comment]
Done when #4 is merged.

**Comment by j042** [comment]
I think this is done, thanks!
